//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nightowlsign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastInstalledSchedule
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Manager { get; set; }
        public string Phone { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<System.DateTime> LastInstalled { get; set; }
    }
}
