//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nightowlsign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        public int id { get; set; }
        public string Model { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> StoreId { get; set; }
    }
}
