//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nightowlsign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignBrightness
    {
        public int Id { get; set; }
        public Nullable<int> SignId { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> BrightnessLevel { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
