//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nightowlsign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreScheduleLog
    {
        public int Id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<bool> InstalledOk { get; set; }
        public System.DateTime DateInstalled { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    }
}
